### ISSUE TITLE
Profile/About page

### ISSUE THREAD

**Issue by kevinmarks** [ChristopherA/LifeWithAlacrityBlog#4]
Need 2 versions - a small one for every page so the h-card authorship works, and probably a more full one to replace the dead link on the old homepage.

I'll make a minimal one, the assign to Chris for more info.

**Comment by kevinmarks** [comment]
firts pass at these done; needs a little layout adjustment, and content choices.

**Comment by ChristopherA** [comment]
Just put short text from twitter page for title.

**Comment by kevinmarks** [comment]
twitter bio propagated ( em-dashes removed, explicit wrapping added)
